#  File: docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_NAME: your_db_name
      DB_USER: your_db_user
      DB_PASS: your_db_password
      DB_HOST: db

volumes:
  pgdata: